apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true" # NOTE: Can't use 'false' due to https://github.com/jetstack/kube-lego/issues/173.
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: your-static-ip-name
    kubernetes.io/tls-acme: "true"
  name: nexus
spec:
  rules:
    - host: containers.example.com
      http:
        paths:
          - backend:
              serviceName: nexus-proxy
              servicePort: 8080
            path: /*
    - host: nexus.example.com
      http:
        paths:
          - backend:
              serviceName: nexus-proxy
              servicePort: 8080
            path: /*
  tls:
    - hosts:
        - containers.example.com
        - nexus.example.com
      secretName: nexus-tls
